<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\VirtualDesktop\VirtualDesktop11-24H2.exe" LogicalName="VirtualDesktopHelper.Resources.VirtualDesktop11-24H2.exe" />
  </ItemGroup>

</Project>
